version: '3'
services:

  controller:
    image: masiroproject/maid_robot_system_for_simulator:v2.0
    container_name: MCAP_environment
    volumes:
      - /mnt/wslg:/mnt/wslg
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=$DISPLAY
      - PULSE_SERVER=$PULSE_SERVER
      - WAYLAND_DISPLAY=$WAYLAND_DISPLAY
      - XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR
    command: /bin/bash -c "./launch_MCAP_environment.sh"
